---
  list:
    103-82-2: 
      name: 苯乙酸
      ml2g: 1.081
    108-24-7: 
      name: 醋酸酐
      ml2g: 1.08
    67-66-3: 
      name: 三氯甲烷
      ml2g: 1.489
    60-29-7: 
      name: 乙醚
      ml2g: 0.714
    110-89-4: 
      name: 哌啶
      ml2g: 0.86
    108-88-3: 
      name: 甲苯
      ml2g: 0.866
    67-64-1: 
      name: 丙酮
      ml2g: 0.79
    78-93-3: 
      name: 甲基乙基酮
      ml2g: 0.804
    7722-64-7: 
      name: 高锰酸钾
    7664-93-9: 
      name: 硫酸
      ml2g: 1.84
    7647-01-0: 
      name: 盐酸
      ml2g: 1.18
    8014-95-7:
      name: 发烟硫酸
      ml2g: 1.84
...

